r=int(input('Enter radius for sphere '))
R= int(input('enter radius of cylinder : '))
h=int(input('enter ht of cy '))
r1=int (input('radius of cone'))
H=int(input('ht of cone'))
print ("volume of sphere = ",4/3*22/7*r*r*r)
print ("area of cylinder = ",22/7*2*R*h)
print ("volume of cy",22/7*R*R*h)
print ('volume of cone = ',1/3*22/7*r1*r1*H)
l=((r1*r1)+(H*H))**(1/2)
print ('area of cone = ',r1*H*l)
